### PR TITLE
allow cbor serializer to serialize larger payloads

### PR DESCRIPTION
**Pull request by om26er**
Fixes https://github.com/crossbario/autobahn-js/issues/565

### CODE REVIEW

**Comment by om26er** [comment]
Without the proposed change this is what shows up in Crossbar logs
```
2022-11-07T23:55:47+0500 [Router     1524143] Traceback (most recent call last):
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/autobahn/wamp/serializer.py", line 278, in unserialize
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/autobahn/wamp/serializer.py", line 768, in unserialize
_cbor2.CBORDecodeEOF: premature end of stream (expected to read 1 bytes, got 0 instead)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/autobahn/wamp/serializer.py", line 280, in unserialize
autobahn.wamp.exception.ProtocolError: invalid serialization of WAMP message: CBORDecodeEOF premature end of stream (expected to read 1 bytes, got 0 instead)

2022-11-07T23:55:47+0500 [Router     1524143] failing WebSocket connection (code=1002): "WAMP Protocol Error (invalid serialization of WAMP message: CBORDecodeEOF premature end of stream (expected to read 1 bytes, got 0 instead))"
```

**Comment by om26er** [comment]
Also added a test that would otherwise fail

**Review by vovchisko — APPROVED** [review]

**Comment by om26er** [comment]
@oberstet what do you think about this one. Does this look good to land ?

**Comment by om26er** [comment]
cleaned up the test. I think we are good now

**Pull request merged**
