### PR TITLE
Replaced msgpack-lite with msgpack5

### PR DESCRIPTION
**Pull request by agronholm**
This fixes subscription IDs being sent to the router as floats due to msgpack-lite's buggy handling of large numbers.

### CODE REVIEW

**Comment by oberstet** [comment]
Does that work in browsers?

**Comment by agronholm** [comment]
Yes, we are using it in our own web app in staging and it's working wonderfully.

**Comment by agronholm** [comment]
It should also be noted that msgpack5 seems to be actively developed, while msgpack-lite hasn't seen any commits in over a year.

**Comment by oberstet** [comment]
I see .. and license is MIT, means also good. ok, cool, thanks! merging.

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
