### PR TITLE
Send extra data while authentication

### LINKED ISSUE #249: Extra authentication data is not being sent to the router
`authextra` is not being sent to the router during authentication of specific types (e.g. `ticket` and `wamp-cra`). 

I don't really know how `autobhan-js` works internally but after a very quick inspection it seems to me that [here](https://github.com/crossbario/autobahn-js/blob/1e7f22e981cd50f187898fafd36e9c7bc545c969/lib/session.js#L1134) `Session.prototype.join` should also have an `authextra` parameter and [here](https://github.com/crossbario/autobahn-js/blob/1e7f22e981cd50f187898fafd36e9c7bc545c969/lib/connection.js#L311) `authextra` should also be passed to the session.

If the fix is really that trivial I'd be glad to make a patch. Let me know if I can help.

Related to https://github.com/crossbario/crossbar/issues/911

### PR DESCRIPTION
**Pull request by Kolyunya**
Fixes #249. This seems to be working just fine but I may be missing something.
Guy lets fix this please. This is a very important feature.

### CODE REVIEW

**Comment by jrocketfingers** [comment]
I've encountered the same problem, and made the exact same corrections down to the letter before I noticed this PR. Can confirm it works.

@Kolyunya, have you had any luck actually building the library? I haven't worked with scons yet and I'm getting `AttributeError: 'SConsEnvironment' object has no attribute 'JavaScript'` when I try to run `make build`/`make build_browser`.

**Comment by Kolyunya** [comment]
@jrocketfingers building guide is incomplete and outdated, I had very hard time building [the library](https://gist.github.com/Kolyunya/156e8056ebc91d69ede551433bbb2238).

**Comment by jrocketfingers** [comment]
I've already done the modifications manually, but thanks :+1: Looking forward to those build instructions.

By the way, since we're on the topic: I haven't utilized `authrole` just yet, but it seems to be an argument in [ApplicationSession.join in autobahn-python](https://github.com/crossbario/autobahn-python/blob/ea4842090a03cf57c09eb0c34359cff4d3cc2b44/autobahn/wamp/protocol.py#L337). Would it make sense to pass it too? Perhaps if a single component could be authenticated for multiple roles it could represent the preferential role.

**Comment by Kolyunya** [comment]
@jrocketfingers yeah, it seems to me that 'authrole' may be useful while authentication too but it should be discussed in a separate issue.

**Comment by jrocketfingers** [comment]
Are there any updates on this? I'd be alright if I could at least build the library.

**Comment by oberstet** [comment]
Sorry for sluggish responsive .. looks good! Thanks for contributing!

**Comment by Kolyunya** [comment]
@oberstet can we please have a release? Thank you!

**Comment by oberstet** [comment]
The `authrole` is normally assigned automatically by the router when the authentication was successful. Generally, a WAMP client *may* also request a specific `authrole`, but the router might deny that or override it.

**Pull request merged**
