### PR TITLE
Fix environment detect

### PR DESCRIPTION
**Pull request by RBukharov**
Use browser WebSocket implementation for Electron apps

### CODE REVIEW

**Comment by oberstet** [comment]
more robust probably:

```
if (process.versions.hasOwnProperty('electron')) {
  // Electron specific code
}else{
}
```
https://github.com/electron/electron/issues/2288#issuecomment-395674352

**Comment by RBukharov** [comment]
You right, I will add ``process.versions.hasOwnProperty('electron')``.

Now there is no electron specific code - it's the same as for browser. So if you agree I wont repeat this code in the separate "if" branch.

**Comment by oberstet** [comment]
cool, thanks for contributing!

**Comment by om26er** [comment]
So I am faced with that issue while playing with Electron and Autobahn, will probably have to wait for a new ABJS release, or maybe I should work on it ?

**Comment by oberstet** [comment]
@om26er maybe help completing this one https://github.com/crossbario/autobahn-js/pull/381 and then do a release? ah, also: let me know if you need sth rgd publishing a new release. not sure .. npm etc

**Comment by om26er** [comment]
> @om26er maybe help completing this one #381 and then do a release? ah, also: let me know if you need sth rgd publishing a new release. not sure .. npm etc

Ok, I am fine with that. That will be my first dive into ABJS, so do bare with me. Though I did implement similar functionality in ABJava that too inspired by ABPy.

I will ask @akiroz first to make sure we don't end up duplicating any effort there.

**Comment by akiroz** [comment]
@om26er Please go ahead, I don't have the time to implement all the mentioned features.

**Pull request merged**
