### PR TITLE
Enable CI

### PR DESCRIPTION
**Pull request by om26er**
First pass at CI for autobahn-js. I tested it by enabling CI on my personal branch and seem things are working "good", see https://travis-ci.org/om26er/autobahn-js

When we merge, please use "squash and merge" button as this PR is loaded with minor commits.

### CODE REVIEW

**Comment by om26er** [comment]
We probably need to enable Slack/IRC notifications sooner, maybe right after this lands ?

**Comment by om26er** [comment]
Individual github issues for the disabled tests https://github.com/crossbario/autobahn-js/issues/412 and https://github.com/crossbario/autobahn-js/issues/413

**Comment by oberstet** [comment]
gonna enable travis now ..

**Comment by oberstet** [comment]
that worked! and runs green .. cool=)

https://travis-ci.org/crossbario/autobahn-js

things we need to complete:

* https://github.com/crossbario/autobahn-js/issues/415
* https://github.com/crossbario/autobahn-js/issues/416

**Pull request merged**
