### PR TITLE
Add missing dependencies

### PR DESCRIPTION
**Pull request by johngeorgewright**
Hey there,

I just tried to build autobahn with `make bundle` and noticed there's a couple of missing dependencies.

### CODE REVIEW

**Comment by oberstet** [comment]
works for me:

```
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js$ make clean
rm -rf build
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js$ make 
scons
scons: Reading SConscript files ...
Building AutobahnJS 0.10.0
scons: done reading SConscript files.
scons: Building targets ...
browserify package/lib/autobahn.js --standalone autobahn -o build/autobahn.js
js_builder(["build/autobahn.min.js"], ["build/autobahn.js"])
/usr/lib/jvm/default-java/bin/java -jar /home/oberstet/compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js build/autobahn.js --js_output_file build/autobahn.min.js
build/autobahn.js:15281: WARNING - Suspicious code. The result of the 'getprop' operator is not being used.
    array.byteLength
    ^

0 error(s), 1 warning(s)
gzipper(["build/autobahn.min.jgz"], ["build/autobahn.min.js"])
checksumsMD5(["build/CHECKSUM.MD5"], ["build/autobahn.js", "build/autobahn.min.js", "build/autobahn.min.jgz"])
checksumsSHA1(["build/CHECKSUM.SHA1"], ["build/autobahn.js", "build/autobahn.min.js", "build/autobahn.min.jgz"])
checksumsSHA256(["build/CHECKSUM.SHA256"], ["build/autobahn.js", "build/autobahn.min.js", "build/autobahn.min.jgz"])
scons: done building targets.
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js$ 
```

**Comment by johngeorgewright** [comment]
And what if you reinstall node modules?

```
rm -rf node_modules
npm i
make clean && make
```

**Comment by oberstet** [comment]
@johngeorgewright ah, yes. right.

```console
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js/package$ rm -rf node_modules/
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js/package$ npm install
WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"2.14.15"})
crypto-js@3.1.6 node_modules/crypto-js

when@3.7.7 node_modules/when

ws@1.0.1 node_modules/ws
├── options@0.0.6
└── ultron@1.0.2

nodeunit@0.9.1 node_modules/nodeunit
└── tap@0.7.1 (inherits@2.0.1, buffer-equal@0.0.2, slide@1.1.6, deep-equal@1.0.1, yamlish@0.0.7, nopt@3.0.6, difflet@0.2.6, mkdirp@0.5.1, runforcover@0.0.2, glob@4.5.3)

browserify@13.0.0 node_modules/browserify
├── htmlescape@1.1.0
├── tty-browserify@0.0.0
├── path-browserify@0.0.0
├── https-browserify@0.0.1
├── os-browserify@0.1.2
├── inherits@2.0.1
├── string_decoder@0.10.31
├── duplexer2@0.1.4
├── constants-browserify@1.0.0
├── stream-browserify@2.0.1
├── isarray@0.0.1
├── defined@1.0.0
├── through2@2.0.1
├── process@0.11.2
├── browser-resolve@1.11.1
├── punycode@1.4.0
├── xtend@4.0.1
├── read-only-stream@2.0.0
├── querystring-es3@0.2.1
├── assert@1.3.0
├── timers-browserify@1.4.2
├── domain-browser@1.1.7
├── deps-sort@2.0.0
├── util@0.10.3
├── events@1.1.0
├── concat-stream@1.5.1 (typedarray@0.0.6)
├── parents@1.0.1 (path-platform@0.11.15)
├── resolve@1.1.7
├── subarg@1.0.0 (minimist@1.2.0)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0, jsonify@0.0.0)
├── has@1.0.1 (function-bind@1.1.0)
├── vm-browserify@0.0.4 (indexof@0.0.1)
├── shasum@1.0.2 (sha.js@2.4.5, json-stable-stringify@0.0.1)
├── labeled-stream-splicer@2.0.0 (stream-splicer@2.0.0)
├── url@0.11.0 (punycode@1.3.2, querystring@0.2.0)
├── buffer@4.5.0 (ieee754@1.1.6, isarray@1.0.0, base64-js@1.1.1)
├── JSONStream@1.1.1 (through@2.3.8, jsonparse@1.2.0)
├── stream-http@2.2.0 (builtin-status-codes@2.0.0, to-arraybuffer@1.0.1)
├── readable-stream@2.0.5 (process-nextick-args@1.0.6, util-deprecate@1.0.2, core-util-is@1.0.2)
├── syntax-error@1.1.5 (acorn@2.7.0)
├── module-deps@4.0.5 (stream-combiner2@1.1.1, detective@4.3.1)
├── browserify-zlib@0.1.4 (pako@0.2.8)
├── glob@5.0.15 (path-is-absolute@1.0.0, inflight@1.0.4, once@1.3.3, minimatch@3.0.0)
├── crypto-browserify@3.11.0 (create-hmac@1.1.4, randombytes@2.0.3, pbkdf2@3.0.4, create-hash@1.1.2, diffie-hellman@5.0.2, create-ecdh@4.0.0, browserify-cipher@1.0.0, browserify-sign@4.0.0, public-encrypt@4.0.0)
├── browser-pack@6.0.1 (umd@3.0.1, combine-source-map@0.7.1)
└── insert-module-globals@7.0.1 (is-buffer@1.1.3, lexical-scope@1.2.0, combine-source-map@0.7.1)
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js/package$ cd ..
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js$ make clean
rm -rf build
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js$ make
scons
scons: Reading SConscript files ...
Building AutobahnJS 0.10.0
scons: done reading SConscript files.
scons: Building targets ...
browserify package/lib/autobahn.js --standalone autobahn -o build/autobahn.js
Error: Cannot find module 'bufferutil' from '/home/oberstet/scm/crossbario/autobahn-js/package/node_modules/ws/lib'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
scons: *** [build/autobahn.js] Error 1
scons: building terminated because of errors.
make: *** [all] Fehler 2
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js$ git pull
remote: Counting objects: 10, done.
remote: Total 10 (delta 7), reused 7 (delta 7), pack-reused 2
Unpacking objects: 100% (10/10), done.
Von github.com:crossbario/autobahn-js
   0e6fe11..028db3e  master     -> origin/master
Aktualisiere 0e6fe11..028db3e
Fast-forward
 package/Makefile     | 2 ++
 package/package.json | 2 ++
 2 files changed, 4 insertions(+)
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js$ make
scons
scons: Reading SConscript files ...
Building AutobahnJS 0.10.0
scons: done reading SConscript files.
scons: Building targets ...
scons: `build/autobahn.js' is up to date.
js_builder(["build/autobahn.min.js"], ["build/autobahn.js"])
/usr/lib/jvm/default-java/bin/java -jar /home/oberstet/compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js build/autobahn.js --js_output_file build/autobahn.min.js
gzipper(["build/autobahn.min.jgz"], ["build/autobahn.min.js"])
checksumsMD5(["build/CHECKSUM.MD5"], ["build/autobahn.js", "build/autobahn.min.js", "build/autobahn.min.jgz"])
checksumsSHA1(["build/CHECKSUM.SHA1"], ["build/autobahn.js", "build/autobahn.min.js", "build/autobahn.min.jgz"])
checksumsSHA256(["build/CHECKSUM.SHA256"], ["build/autobahn.js", "build/autobahn.min.js", "build/autobahn.min.jgz"])
scons: done building targets.
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js$ 
```

**Comment by johngeorgewright** [comment]
Ta very moosh. Now I should also be able to use this as a dependency within my browserify bundle.

**Pull request merged**
