### PR TITLE
put google-closure-compiler in devDeps

### PR DESCRIPTION
**Pull request by tyv**
I was trying to run all the environment to run tests, but failed after hour trying.
This is related to wix/kissfs/issues/37

### CODE REVIEW

**Comment by tyv** [comment]
closes #280

**Comment by tyv** [comment]
@oberstet I am sorry to ping you directly, but this is stopper for one of our projects, would be really helpful to get this update available. Thanks.

**Comment by oberstet** [comment]
@tyv sorry for the hassles and thanks for the PR. I push a new release

**Comment by tyv** [comment]
many thanks!

**Pull request merged**
