### PR TITLE
Autopings for browser-based websocket transport

### PR DESCRIPTION
**Pull request by karolyi**
Hey,

Since the websocket transport in the browser doesn't support autopings yet
(no browser supports it out of the box, they only respond to the pings),
I'm implementing it with this PR.

### CODE REVIEW

**Comment by oberstet** [comment]
thanks for chiming in! I've had a quick look .. but:

- anything should ideally have an issue _first_ to discuss, since eg:
- browsers don't expose websocket API to send pings, so I'm confused what this is all about in the first place
- the whitespace reformatting makes this PR unreadable
- we don't follow the "google styleguide"

so best would really be to first file an issue to clarify what's the goal etc .. sorry, closing this PR hence

**Comment by karolyi** [comment]
@oberstet, aside from all the other points you've made, I'd like to address this one before I proceed any further:
> - browsers don't expose websocket API to send pings
AFAIK, you can compose a binary packet with the ping opcode header itself and send it with the `websocket.send()`, just like you would send an ordinary packet. Haven't tested it yet, that's where I'm currently at but I've been derailed by other things. So the question would be, am I right assuming that composing the binary package is doable, or do you have evidence that it can't be done?

**Comment by karolyi** [comment]
Okay, looks like I'll be answering my own question. Even if you compose a binary packet with the 0x09 opcode (ping, that is), browsers will encapsulate those as 'binary', so basically putting a 0x02 header before them, so sending pings in the binary way is impossible. Here's the exercise I just had:

```javascript
ws = new WebSocket('ws://test.localdomain:8000/ws/test/echo/')
ws.send(new Uint8Array([9,3, 1,2,3])) // Constructed binary ping packet
```

Chrome and Firefox just encapsulates this packet as a binary one:

image


About native browser support:
- Chrome doesn't support client ping because it would break their devtools protocols (?!). Weird, but here's the issue report, with my comments on it: https://bugs.chromium.org/p/chromium/issues/detail?id=706002
- Firefox (version 62 at present time) has a configuration setting 'network.websocket.timeout.ping.request', that is set to 0, can be overridden by users, but no JS API exists for it.

Haven't checked other browsers, but it seems having the JS API extended with configurable protocol ping options is a pipe dream. It also has theoretical issues, as it could drain the battery on mobile devices having websocket handler web applications run in the background. Browsers try to rely on the more low-level TCP keepalive option, but that is also problematic to use since the TCP connection itself can be handled by a cloud load balancer that has no way of checking if the application behind is dead. Moreover, I found numerous reports on Chrome recognizing a dead/broken TCP connection only after 18 minutes.

All in all, I'd vote for the configurable JS API option, if my vote would matter.

Just leaving the result of my investigation here for other people who'd arrive here after me with looking for the same problem.

**Comment by oberstet** [comment]
Yes, browsers don't expose this .. no browser .. because it is not specified in the W3C API for WebSocket, only in the IETF protocol spec for WebSocket - IOW, it is implementation dependent if and how it is exposed to user code.

**Pull request closed without merging**
