### PR TITLE
Allow a call to be cancelled

### LINKED ISSUE #309: Support call cancelling
According to [this line in the code][1] it looks like autobahn-js does not support call cancelling. I also do not see any reference to it in the [Progressive Results section of the API doc][2].

Is it correct that there currently is no way for an autobahnjs caller to cancel a progressive call? Is this a planned feature?

Unsure of how this would even be designed. One way might be something like this:

    var d = session.call('com.myapp.longop', [10], {}, {receive_progress: true});
    d.cancel()

Which would mimic the [autobahn|python style][3]. But I believe `d` is just a standard deferred from whichever promise library is being used. Perhaps

    var d = session.call('com.myapp.longop', [10], {}, {receive_progress: true});
    d.reject()

could be used and `session.call` would have added an `onReject` handler which will send a `WAMP.CANCEL` message in the case of `receive_progress: true`?

  [1]: https://github.com/crossbario/autobahn-js/blob/37fb3232ff0842c166ef1d86265602d2b1292d26/lib/session.js#L34
  [2]: https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md#progressive-results
  [3]: https://github.com/crossbario/autobahn-python/blob/224370cd9dda312fc0583b61ed416b3f4d0e00d0/docs/work/programming.rst#canceling-calls

### PR DESCRIPTION
**Pull request by Jopie64**
This would fix #309

Please let me know whether this is OK.

### CODE REVIEW

**Comment by oberstet** [comment]
not really;) pls see https://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#rfc.section.14.3.4

**Comment by Jopie64** [comment]
I don't see whats wrong according to the specs...
I even tested it with the autobahn router and it seems to work...
Or should it **always** supply a mode and is an absent mode invalid protocol behavior?

**Comment by oberstet** [comment]
@Jopie64 ok, sorry, maybe I was too quick! we need to test this with Crossbar.io, yeah. I need some calm minutes to get into the details .. too much other stuff ringing in my brain right now;) Thanks for contributing!

**Comment by Jopie64** [comment]
No problem :)
Oh and this only *partly* fixes #309 because it now only supports call cancelling on the caller side.

Also, thinking about it, it might now cause a leak when the mode is other than 'kill' because it will not remove the call from the pending call list...

**Comment by Jopie64** [comment]
Now the leak is also fixed :)

**Comment by oberstet** [comment]
this looks good for me. I haven't had time to test it myself, but I think it is non-invasive enough (doesn't break existing behavior) so that we can test this in the field. we're gonna ship a new release soonish, so I just merge this now.

**Pull request merged**
