### PR TITLE
Implement autoping for Node.js websocket transport #380

### LINKED ISSUE #380: Add WebSocket auto ping/pong (heartbeating) on Node.js
Broken web socket connections on node.js are not closed properly.

Ref.
https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

### PR DESCRIPTION
**Pull request by akiroz**
Fixes #380

### CODE REVIEW

**Comment by oberstet** [comment]
thanks for your work! this is a good start. I have added some notes here how we could improve a bit and bring the feature on-par with ABPy:

* https://github.com/crossbario/autobahn-js/issues/380#issuecomment-422270535

and these pointers to ABPy might be useful to look at (steal the implementation / adapt to JS):

* _sendAutoPing: https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/protocol.py#L1863
* auto ping/pong processing: https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/protocol.py#L1718

**Comment by om26er** [comment]
Hello @akiroz, thanks for your effort. Are you working on this or planning to work on this ? in either case I am willing to take that on and implement it as suggested by @oberstet

**Comment by akiroz** [comment]
@om26er Please go ahead, I don't have the time to implement all the mentioned features.

**Comment by oberstet** [comment]
superseded by https://github.com/crossbario/autobahn-js/pull/382

**Pull request closed without merging**
